# Generated by Django 4.1 on 2022-08-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chistes',
            fields=[
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('icon_url', models.URLField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('url', models.URLField()),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
    ]
